import pc from "picocolors";
import { DBConfig } from "../src/core/types.js";
import { createDBAdapter } from "../src/core/factory.js";
import fs from "fs/promises";
import path from "path";

function mapSqlTypeToTs(sqlType: string): string {
  const type = sqlType.toLowerCase();
  if (type.includes("int") || type.includes("num") || type.includes("float") || type.includes("double") || type.includes("real")) {
    return "number";
  }
  if (type.includes("bool") || type === "tinyint(1)") {
    return "boolean";
  }
  if (type.includes("char") || type.includes("text") || type.includes("uuid") || type.includes("string")) {
    return "string";
  }
  if (type.includes("date") || type.includes("time")) {
    return "Date";
  }
  if (type.includes("json")) {
    return "any";
  }
  return "string"; // fallback
}

export async function runGenerateTypesCommand(dbConfig: DBConfig) {
  if (dbConfig.type === "unknown") {
    console.log(pc.red("Error: No database connection found. Cannot generate types."));
    process.exit(1);
  }

  const adapter = createDBAdapter(dbConfig);
  console.log(pc.cyan(`\nScanning database to generate TypeScript interfaces...`));

  try {
    const allTables = await adapter.getTables();
    
    if (allTables.length === 0) {
      console.log(pc.yellow("No tables found in the database."));
      process.exit(0);
    }

    let tsCode = `// Generated by TerDB CLI\n// Database: ${dbConfig.type.toUpperCase()}\n\n`;

    for (const table of allTables) {
      const interfaceName = table.charAt(0).toUpperCase() + table.slice(1).replace(/_([a-z])/g, (g) => g[1].toUpperCase()); // camelCase
      tsCode += `export interface ${interfaceName} {\n`;
      
      const schema = await adapter.getSchema(table);
      for (const col of schema) {
        const tsType = mapSqlTypeToTs(col.type);
        const optionalFlag = col.nullable ? "?" : "";
        tsCode += `  ${col.name}${optionalFlag}: ${tsType};\n`;
      }
      tsCode += `}\n\n`;
    }

    const outPath = path.resolve(process.cwd(), "terdb-types.d.ts");
    await fs.writeFile(outPath, tsCode.trim() + "\n", "utf-8");

    console.log(pc.green(`✔ TypeScript interfaces generated successfully!`));
    console.log(pc.white(`Output saved to: ${pc.bold(outPath)}`));
  } catch (e: any) {
    console.log(pc.red(`\n✘ Failed to generate types: ${e.message}`));
  } finally {
    await adapter.close();
  }

  process.exit(0);
}
